spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_read?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root



#数据库连接池使用Druid
datasource:
  type: com.alibaba.druid.pool.DruidDataSource